export const data = {
  title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  body: `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies eleifend lorem, posuere viverra sem hendrerit a. Suspendisse at libero eget nisi laoreet ultricies. Donec eu consequat eros. Nam quis erat at urna mollis imperdiet. Integer imperdiet feugiat facilisis. Vestibulum quis nisi ullamcorper, pretium nulla a, ornare turpis. Nulla sed massa nec sapien posuere pretium. Morbi vel consequat nulla. In fringilla diam id laoreet elementum. Pellentesque luctus tempus arcu sit amet pulvinar. Maecenas condimentum placerat faucibus. Nulla eget ipsum vitae magna hendrerit vulputate. Phasellus ultricies est vel imperdiet euismod. Vivamus ligula tellus, blandit in erat eget, fringilla eleifend elit.

  Phasellus bibendum placerat nunc, eget consectetur eros convallis interdum. Phasellus imperdiet pulvinar erat, quis pulvinar sapien fringilla et. Proin scelerisque finibus purus, a aliquam mauris accumsan quis. Donec ut pretium velit. Pellentesque elementum odio nec ultricies ornare. Quisque tincidunt ipsum sagittis erat cursus tempus. Phasellus dapibus faucibus erat id efficitur. Sed sagittis efficitur ipsum vel venenatis. Curabitur et nunc ac neque feugiat placerat non vitae nibh. Curabitur volutpat, eros eu consectetur eleifend, dui libero rutrum turpis, a varius velit sem non orci. Aliquam erat volutpat. Sed pharetra tellus ante, at venenatis urna molestie id. Nullam venenatis, orci id malesuada luctus, diam urna rhoncus arcu, vel vulputate arcu dolor non diam. Etiam aliquet pharetra orci ut auctor. Sed porta sem arcu.
  
  Cras blandit quam ac arcu tincidunt, a congue enim venenatis. Nullam ultrices finibus justo interdum consectetur. Phasellus vitae felis at sem volutpat varius a sed massa. Donec hendrerit mollis sollicitudin. Pellentesque tellus est, viverra ac pellentesque eu, lobortis et sapien. Nunc nec tellus porttitor, pulvinar mauris a, condimentum odio. Quisque magna nunc, cursus a felis at, suscipit tristique mi. Curabitur luctus pharetra quam in vestibulum. Fusce rhoncus malesuada ligula, at faucibus mi volutpat vel.
  `,
};
